### ISSUE TITLE
Ligatures not displaying

### ISSUE THREAD

**Issue by Lokilotus** [leo3065/Devotee-Plus#1]
When using the font, ligatures (e.g. V_c) do not appear. I initially thought this was a to-do, and was happy to contribute a PR to fix this, before playing around in FontForge and realising the font was working as intended there. I am unsure what has broken here so instead I am giving a bug report!

Expected font output, as given by FontForge's Metric window:
![image](https://github.com/leo3065/Devotee-Plus/assets/2342253/050095d2-678c-43bd-a9e2-e53ae7f344c5)

Actual font output, as given by Word/Office Professional Plus 2021:
![image](https://github.com/leo3065/Devotee-Plus/assets/2342253/1ec46c3d-0c53-4d96-8c34-0d1cad853b2a)

Love the font and the game, so more than happy to help get this fixed if I can - do let me know!

**Comment by Lokilotus** [comment]
Upon further research, this issue is not with the font, but with Word.

It turns out that for some ungodly reason Word decides to turn off certain features, like ligatures. Compatability mode also seems to play a part.

As you can see in the screenshot below, the ligatures are now working, as well as the setting you need to turn off to make them work in word.

![image](https://github.com/leo3065/Devotee-Plus/assets/2342253/ecba6086-36b9-4d88-af84-5eaf6a0838b2)

The following links were helpful in resolving this issue and may be helpful to include in the Readme:
https://www.reddit.com/r/FontForge/comments/vx9ltb/ligatures_wont_work_its_imposible/
https://redneptun.net/nekophilia-font/msoffice_en.html
https://answers.microsoft.com/en-us/msoffice/forum/all/opentype-advanced-features-greyed-out/197fe5ff-caed-42c3-9fa9-2e17194dbda7

Thanks again for the wonderful font! :D

**Comment by leo3065** [comment]
I used LibreOffice so I didn't encounter the issue when testing. I believe that that some people on Reddit had also reported this. Good to know that there's way to enable it in Word.
